project_name: go-versioninfo
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w {{ if index .Env "VERSION" }}-X github.com/ngyewch/go-versioninfo/v.Version={{ .Env.VERSION }}{{ end }} {{ if index .Env "COMMIT" }}-X github.com/ngyewch/go-versioninfo/v.Commit={{ .Env.COMMIT }}{{ end }} {{ if index .Env "COMMIT_TIMESTAMP" }}-X github.com/ngyewch/go-versioninfo/v.CommitTimestamp={{ .Env.COMMIT_TIMESTAMP }}{{ end }}
archives:
  - format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
release:
  disable: false
